os:
#  - linux
  - osx

env:
  - XQUARTZ_VERSION=2.7.7

language: c++

before_install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; sudo apt-get install -y gfortran; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update ; brew outdated cmake || brew upgrade cmake ; fi
    - cmake --version
    - curl -L -O http://xquartz.macosforge.org/downloads/SL/XQuartz-${XQUARTZ_VERSION}.dmg;
    - hdiutil mount XQuartz-${XQUARTZ_VERSION}.dmg
    - sudo installer -store -pkg /Volumes/XQuartz-${XQUARTZ_VERSION}/XQuartz.pkg -target /
    - hdiutil unmount /Volumes/XQuartz-${XQUARTZ_VERSION}

script:
    - cd ..
    - mkdir _build
    - cd _build
    - cp ../pcmdi_metrics/install_metrics.bash .
    - bash ./install_metrics.bash
    - source ./PCMDI_METRICS/bin/setup_runtime.sh
    - cd ./PCMDI_METRICS/tmp/metrics
    - python test/test_suite.py
