os:
  - linux
#  - osx

language: c++

before_install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; sudo apt-get install -y gfortran; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pushd $HOME && mkdir cmake3.1 && cd cmake3.1 && (curl "http://www.cmake.org/files/v3.1/cmake-3.1.0-Linux-x86_64.tar.gz" | gunzip -c | tar x) && cd cmake-*/bin && export PATH="${PWD}:${PATH}"; popd; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update ; brew outdated cmake || brew upgrade cmake ; fi
    - cmake --version

script:
    - cd ..
    - mkdir _build
    - cd _build
    - cp ../pcmdi_metrics/install_metrics.bash
    - bash ./install_metrics.bash
    - source ./PCMDI_METRICS/bin/setup_runtime.sh
    - python test/test_suite.py
