package:
    name: pcmdi_metrics
    version: master

source:
    git_rev: master
    git_url: git://github.com/PCMDI/pcmdi_metrics

build:
  string: PMP
  script: python setup.py install
 
requirements:
  build:
    - python
    - setuptools
    - numpy <=1.9.2
  run:
    - uvcdat

about:
    home:  http://gitub.com/PCMDI/pcmdi_metrics



